version: '3.8'

services:
  mari_php:
    image: richarvey/nginx-php-fpm:php5
    container_name: mari_php
    volumes:
      - ./www:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mari_db

  mari_db:
    image: mariadb:10.1
    container_name: mari_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: exampledb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql

volumes:
  db_data:
